---
Resources:
  ServerlessKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: ${env:STAGE}-serverless-kinesis-streams
      ShardCount: 1
  ServerlessDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${env:STAGE}-serverless-kinesis-dynamodb
