service: serverless-kinesis

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${env:STAGE}-*
    - Effect: Allow
      Action:
        - kinesis:DescribeStream
        - kinesis:PutRecord
        - kinesis:ListStreams
        - kinesis:GetRecords
        - kinesis:GetShardIterator
      Resource: arn:aws:kinesis:${self:provider.region}:*:stream/${env:STAGE}-*

custom:
  currentStage: ${opt:stage, self:provider.stage}

package:
  exclude:
    - README.md
    - .envrc
    - .envrc.skeleton
    - .eslintrc.js
    - yarn.lock

functions:
  producer:
    handler: src/producer.execute
    environment:
      STAGE: ${self:custom.currentStage}
    events:
      - http:
          path: /webhook
          method: post
  consumer:
    handler: src/consumer.execute
    environment:
      STAGE: ${self:custom.currentStage}
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - ServerlessKinesisStream
              - Arn
          batchSize: 10
          startingPosition: LATEST

resources: ${file(resources.yml)}

plugins:
  - serverless-webpack
