service: serverless-kinesis

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${env:STAGE}-*
    - Effect: Allow
      Action:
        - kinesis:DescribeStream
        - kinesis:PutRecord
        - kinesis:ListStreams
        - kinesis:GetRecords
        - kinesis:GetShardIterator
      Resource: arn:aws:kinesis:${self:provider.region}:*:stream/${env:STAGE}-*

package:
  exclude:
    - README.md
    - .envrc
    - .envrc.skeleton
    - .eslintrc.js
    - package.json
    - node_modules/**
    - yarn.lock

functions:
  producer:
    handler: src/producer.execute
    environment:
      STAGE: ${env:STAGE}
    events:
      - http:
          path: /webhook
          method: post
  consumer:
    handler: src/consumer.execute
    environment:
      STAGE: ${env:STAGE}
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - ServerlessKinesisStream
              - Arn
          batchSize: 10
          startingPosition: LATEST

resources:
  Resources:
    ServerlessKinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${env:STAGE}-serverless-kinesis-streams
        ShardCount: 1
    ServerlessDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${env:STAGE}-serverless-kinesis-dynamodb

plugins:
  - serverless-plugin-typescript
